language: r
r:
  - release
  - devel
sudo: false
cache: packages


before_install:
  - wget https://github.com/jgm/pandoc/releases/download/1.17.0.2/pandoc-1.17.0.2-1-amd64.deb
  - sudo dpkg -i pandoc-1.17.0.2-1-amd64.deb

r_github_packages:
- jimhester/covr
#- jimhester/lintr

after_success:
#- Rscript -e 'lintr::lint_package()'
- Rscript -e 'library(covr);codecov()'

after_failure:
- Rscript -e 'library(covr);codecov()'

notifications:
  email:
    on_success: change
    on_failure: change
