language: r
r:
  - release
  - devel
sudo: false
cache: packages

addons:
  apt:
    packages:
      - pandoc

r_github_packages:
- jimhester/covr
#- jimhester/lintr

after_success:
#- Rscript -e 'lintr::lint_package()'
- Rscript -e 'library(covr);codecov()'

after_failure:
- Rscript -e 'library(covr);codecov()'

notifications:
  email:
    on_success: change
    on_failure: change
